version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/reactbkk3
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run: |
          yarn
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v1
      - run: |
          yarn run build
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]
          then
            git config --global user.name "CircleCI" && git config --global user.email "circleci@spacet.me" && yarn run deploy
          else
            echo 'Not master branch, therefore not deploying ^_^'
          fi
